"""rename generated_text to route_text

Revision ID: f21d291b4b04
Revises: a22795864a24
Create Date: 2025-10-29 06:14:47.684748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f21d291b4b04'
down_revision: Union[str, Sequence[str], None] = 'a22795864a24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generated_routes', sa.Column('route_text', sa.Text(), nullable=False))
    op.drop_column('generated_routes', 'generated_text')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generated_routes', sa.Column('generated_text', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('generated_routes', 'route_text')
    # ### end Alembic commands ###
